### PR TITLE
Drop MBS message objects

### PR DESCRIPTION
**Pull request by tkdchen**
This is a corresponding change of
https://pagure.io/fm-orchestrator/pull-request/1502, where message
objects are dropped for migrating to Celery.

Signed-off-by: Chenxiong Qi <cqi@redhat.com>

### CODE REVIEW

**Comment by tkdchen** [comment]
I'll rebase this pr onto #14 after it's merged.

**Comment by tkdchen** [comment]
The changes in this PR is ready for review.

**Comment by mikebonnet** [comment]
Looks good in general. I'll re-review after the rebase.

**Comment by tkdchen** [comment]
Ping for review.

**Comment by mikebonnet** [comment]
This looks good, thanks!

**Pull request merged**
